# Generated by Django 3.0 on 2019-12-12 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rastreo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='placa',
            field=models.CharField(help_text='Introduce Placa', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='ultima_pos_lat',
            field=models.CharField(help_text='Introduce Última latitud', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='ultima_pos_long',
            field=models.CharField(help_text='Introduce Última longitud', max_length=20),
        ),
    ]
