# Generated by Django 3.0 on 2019-12-12 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rastreo', '0002_auto_20191212_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='ultima_pos_lat',
            field=models.DecimalField(decimal_places=7, help_text='Introduce Última latitud', max_digits=11),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='ultima_pos_long',
            field=models.DecimalField(decimal_places=7, help_text='Introduce Última longitud', max_digits=12),
        ),
    ]
